// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.26.1
// source: proto/syralon/events/event_service.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *WriteEventsRequest) Reset() {
	*x = WriteEventsRequest{}
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEventsRequest) ProtoMessage() {}

func (x *WriteEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEventsRequest.ProtoReflect.Descriptor instead.
func (*WriteEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_syralon_events_event_service_proto_rawDescGZIP(), []int{0}
}

func (x *WriteEventsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type WriteEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WriteEventsResponse) Reset() {
	*x = WriteEventsResponse{}
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEventsResponse) ProtoMessage() {}

func (x *WriteEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEventsResponse.ProtoReflect.Descriptor instead.
func (*WriteEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_syralon_events_event_service_proto_rawDescGZIP(), []int{1}
}

type PrepareEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *PrepareEventsRequest) Reset() {
	*x = PrepareEventsRequest{}
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareEventsRequest) ProtoMessage() {}

func (x *PrepareEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareEventsRequest.ProtoReflect.Descriptor instead.
func (*PrepareEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_syralon_events_event_service_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareEventsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type PrepareEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *PrepareEventsResponse) Reset() {
	*x = PrepareEventsResponse{}
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareEventsResponse) ProtoMessage() {}

func (x *PrepareEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareEventsResponse.ProtoReflect.Descriptor instead.
func (*PrepareEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_syralon_events_event_service_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareEventsResponse) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CommitEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *CommitEventsRequest) Reset() {
	*x = CommitEventsRequest{}
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitEventsRequest) ProtoMessage() {}

func (x *CommitEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitEventsRequest.ProtoReflect.Descriptor instead.
func (*CommitEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_syralon_events_event_service_proto_rawDescGZIP(), []int{4}
}

func (x *CommitEventsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CommitEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommitEventsResponse) Reset() {
	*x = CommitEventsResponse{}
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitEventsResponse) ProtoMessage() {}

func (x *CommitEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syralon_events_event_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitEventsResponse.ProtoReflect.Descriptor instead.
func (*CommitEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_syralon_events_event_service_proto_rawDescGZIP(), []int{5}
}

var File_proto_syralon_events_event_service_proto protoreflect.FileDescriptor

var file_proto_syralon_events_event_service_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x79, 0x72, 0x61,
	0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x20, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x12,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x15, 0x0a, 0x13, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x45, 0x0a, 0x14, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2d, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x29, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x27, 0x0a, 0x13, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x8d, 0x02, 0x0a, 0x0c,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x05,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x79, 0x72, 0x61,
	0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56,
	0x0a, 0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x24, 0x2e, 0x73, 0x79, 0x72, 0x61,
	0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x12, 0x23, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f, 0x6e, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x72, 0x61, 0x6c, 0x6f,
	0x6e, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_syralon_events_event_service_proto_rawDescOnce sync.Once
	file_proto_syralon_events_event_service_proto_rawDescData = file_proto_syralon_events_event_service_proto_rawDesc
)

func file_proto_syralon_events_event_service_proto_rawDescGZIP() []byte {
	file_proto_syralon_events_event_service_proto_rawDescOnce.Do(func() {
		file_proto_syralon_events_event_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_syralon_events_event_service_proto_rawDescData)
	})
	return file_proto_syralon_events_event_service_proto_rawDescData
}

var file_proto_syralon_events_event_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_syralon_events_event_service_proto_goTypes = []any{
	(*WriteEventsRequest)(nil),    // 0: syralon.events.WriteEventsRequest
	(*WriteEventsResponse)(nil),   // 1: syralon.events.WriteEventsResponse
	(*PrepareEventsRequest)(nil),  // 2: syralon.events.PrepareEventsRequest
	(*PrepareEventsResponse)(nil), // 3: syralon.events.PrepareEventsResponse
	(*CommitEventsRequest)(nil),   // 4: syralon.events.CommitEventsRequest
	(*CommitEventsResponse)(nil),  // 5: syralon.events.CommitEventsResponse
	(*Event)(nil),                 // 6: syralon.events.Event
}
var file_proto_syralon_events_event_service_proto_depIdxs = []int32{
	6, // 0: syralon.events.WriteEventsRequest.events:type_name -> syralon.events.Event
	6, // 1: syralon.events.PrepareEventsRequest.events:type_name -> syralon.events.Event
	0, // 2: syralon.events.EventService.Write:input_type -> syralon.events.WriteEventsRequest
	2, // 3: syralon.events.EventService.Prepare:input_type -> syralon.events.PrepareEventsRequest
	4, // 4: syralon.events.EventService.Commit:input_type -> syralon.events.CommitEventsRequest
	1, // 5: syralon.events.EventService.Write:output_type -> syralon.events.WriteEventsResponse
	3, // 6: syralon.events.EventService.Prepare:output_type -> syralon.events.PrepareEventsResponse
	5, // 7: syralon.events.EventService.Commit:output_type -> syralon.events.CommitEventsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_syralon_events_event_service_proto_init() }
func file_proto_syralon_events_event_service_proto_init() {
	if File_proto_syralon_events_event_service_proto != nil {
		return
	}
	file_proto_syralon_events_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_syralon_events_event_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_syralon_events_event_service_proto_goTypes,
		DependencyIndexes: file_proto_syralon_events_event_service_proto_depIdxs,
		MessageInfos:      file_proto_syralon_events_event_service_proto_msgTypes,
	}.Build()
	File_proto_syralon_events_event_service_proto = out.File
	file_proto_syralon_events_event_service_proto_rawDesc = nil
	file_proto_syralon_events_event_service_proto_goTypes = nil
	file_proto_syralon_events_event_service_proto_depIdxs = nil
}
